---
{{- if and .Values.metrics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: unifi-poller
type: Opaque
data:
  password: {{ .Values.metrics.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-crt-password
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: unifi-poller
type: Opaque
data:
  password: YWlyY29udHJvbGVudGVycHJpc2U=
{{- end }}